AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visit-counter-lambda

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  VisitCounterFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
        - VPCAccessPolicy: {}
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        IncrementVisitCounter:
          Type: Api
          Properties:
            RestApiId: !Ref GatewayApi
            Auth:
              ApiKeyRequired: true
            Path: /increment
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-0fb24d9929c7e1415
        SubnetIds:
          - subnet-0061846dc0cdd8524
          - subnet-086ab84c8e0aa9cde
      Environment:
        Variables:
          REDIS_HOST: !GetAtt ValkeyInstance.PrimaryEndPoint.Address

  VisitCounterApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: VisitCounterApiKey
      Enabled: true

  VisitCounterUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref GatewayApi
          Stage: Prod
      UsagePlanName: VisitCounterUsagePlan

  VisitCounterUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref VisitCounterApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref VisitCounterUsagePlan

  ValkeyInstance:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Valkey instance
      CacheNodeType: cache.t3.micro
      Engine: valkey
      AutomaticFailoverEnabled: false
      TransitEncryptionEnabled: false
      NumCacheClusters: 1
      SecurityGroupIds:
        - sg-08cc7328e9e33fffa
      CacheSubnetGroupName: !Ref ValkeySubnetGroup

  ValkeySubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet group for Valkey instance"
      SubnetIds:
        - subnet-0061846dc0cdd8524
        - subnet-086ab84c8e0aa9cde

  GatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: GatewayApi
      StageName: Prod

Outputs:
  GatewayApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${GatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/increment/"
  VisitCounterFunction:
    Description: Visit Counter Lambda Function ARN
    Value: !GetAtt VisitCounterFunction.Arn
  VisitCounterFunctionIamRole:
    Description: Implicit IAM Role created
    Value: !GetAtt VisitCounterFunctionRole.Arn