AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visit-counter-lambda

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  VisitCounterFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        IncrementVisitCounter:
          Type: Api
          Properties:
            RestApiId: !Ref GatewayApi
            Path: /increment
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-0123456789abcdef0
        SubnetIds:
          - subnet-0123456789abcdef0
          - subnet-abcdef0123456789
      Environment:
        Variables:
          REDIS_HOST: !GetAtt RedisCluster.PrimaryEndPoint.Address

  RedisInstance:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - sg-0123456789abcdef0
      CacheSubnetGroupName: !Ref RedisSubnetGroup

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet group for Redis instance"
      SubnetIds:
        - subnet-0123456789abcdef0
        - subnet-abcdef0123456789

  RedisInstanceAddress:
    Description: Redis Instance Endpoint
    Value: !GetAtt RedisInstance.PrimaryEndPoint.Address

  GatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: GatewayApi
      StageName: Prod

Outputs:
  GatewayApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${GatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/increment/"
  VisitCounterFunction:
    Description: Visit Counter Lambda Function ARN
    Value: !GetAtt VisitCounterFunction.Arn
  VisitCounterFunctionIamRole:
    Description: Implicit IAM Role created
    Value: !GetAtt VisitCounterFunctionRole.Arn