AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  visit-counter-lambda

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  VisitCounterFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
        - VPCAccessPolicy: {}
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        IncrementVisitCounter:
          Type: Api
          Properties:
            RestApiId: !Ref GatewayApi
            Path: /increment
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-0fb24d9929c7e1415
        SubnetIds:
          - subnet-0061846dc0cdd8524
          - subnet-086ab84c8e0aa9cde
      Environment:
        Variables:
          REDIS_HOST: !GetAtt RedisInstance.RedisEndpoint.Address

  RedisInstance:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - sg-08cc7328e9e33fffa
      CacheSubnetGroupName: !Ref RedisSubnetGroup

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subnet group for Redis instance"
      SubnetIds:
        - subnet-0061846dc0cdd8524
        - subnet-086ab84c8e0aa9cde

  GatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: GatewayApi
      StageName: Prod

Outputs:
  GatewayApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${GatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/increment/"
  VisitCounterFunction:
    Description: Visit Counter Lambda Function ARN
    Value: !GetAtt VisitCounterFunction.Arn
  VisitCounterFunctionIamRole:
    Description: Implicit IAM Role created
    Value: !GetAtt VisitCounterFunctionRole.Arn